### ISSUE TITLE
SQL injection issue in your code

### ISSUE THREAD

**Issue by h4wldev** [hyemdooly/Sinabro_back-end#3]
You only wrote the string format (%s) when writing SQL query string. Even what get from users. 

It is a very dangerous code, That is enough to get a SQL injection attack.

I recommend, Change the Query string from `SELECT %s FROM words WHERE %s='%s'`  to `SELECT %s FROM words WHERE ?=?` or `SELECT %s FROM words WHERE %s=?` with checking area_original

**Comment by hyemdooly** [comment]
`select_query = "SELECT %s FROM words WHERE %s = ?"  cursor.execute(select_query % (area_translated, area_original), word)`

> sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 6 supplied.

It doesn't work. :(

**Comment by h4wldev** [comment]
```python
select_query = "SELECT %s FROM words WHERE %s = (?)" % (area_translated, area_original)
cursor.execute(select_query, (word, ))
```

Try this code

**Comment by hyemdooly** [comment]
Solve it! Thank you!
